name: Build and Package Project

# 允许手动触发工作流
on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: windows-latest  # 使用 Windows 环境，因为要下载 Windows 二进制文件

    steps:
      # 1. 克隆 https://github.com/shinnpuru/VoiceTransl.git 的 main 分支
      - name: Clone VoiceTransl repository
        uses: actions/checkout@v3
        with:
          repository: shinnpuru/VoiceTransl
          ref: main
          path: VoiceTransl

      # 调试步骤：查看当前目录内容
      - name: List current directory contents
        shell: pwsh
        run: Get-ChildItem

      # 2. 删除 llama 文件夹
      - name: Delete llama folder
        run: |
          Remove-Item -Recurse -Force .\VoiceTransl\llama
        shell: powershell

      # 3. 下载最新的 llama-【release tag】-bin-win-sycl-x64.zip 并解压重命名为 llma
      - name: Download and extract llama binary
        run: |
          # 获取最新的 release tag
          $releases = Invoke-RestMethod -Uri "https://api.github.com/repos/ggerganov/llama.cpp/releases"
          $latestRelease = $releases | Where-Object { $_.tag_name -like "*-bin-win-sycl-x64" } | Select-Object -First 1
          $downloadUrl = $latestRelease.assets | Where-Object { $_.name -like "llama-*-bin-win-sycl-x64.zip" } | Select-Object -ExpandProperty browser_download_url

          # 下载 zip 文件
          Invoke-WebRequest -Uri $downloadUrl -OutFile "llama.zip"

          # 解压并重命名
          Expand-Archive -Path "llama.zip" -DestinationPath ".\VoiceTransl\llma"
        shell: powershell

      # 4. 安装 Python 依赖并使用 PyInstaller 构建项目
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # 可以根据项目需求调整 Python 版本

      - name: Install dependencies and build project
        working-directory: ./VoiceTransl
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller app.spec
        shell: powershell

      # 5. 将构建好的项目打包上传
      - name: Package and upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-project
          path: ./VoiceTransl/dist
