name: Build and Upload ByDoubao

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      # 1. 克隆 https://github.com/shinnpuru/VoiceTransl.git main 分支
      - name: Checkout VoiceTransl repository
        uses: actions/checkout@v3
        with:
          repository: shinnpuru/VoiceTransl
          ref: main

      # 2. 切换到克隆项目的根目录
      - name: Change directory to project root
        shell: pwsh
        run: Set-Location -Path ${{ github.workspace }}

      # 3. 删除克隆项目中的 llma 文件夹
      - name: Delete llma folder
        shell: pwsh
        run: |
          if (Test-Path -Path "llma") {
            try {
              Remove-Item -Path "llma" -Recurse -Force -ErrorAction Stop
              Write-Host "Successfully deleted the llma folder."
            } catch {
              Write-Error "Failed to delete the llma folder: $_"
              throw
            }
          } else {
            Write-Host "The llma folder does not exist."
          }

      # 4. 下载最新的包含 llama-【release tag】-bin-win-sycl-x64.zip 的 release 并解压
      - name: Download and extract llama zip
        shell: pwsh
        run: |
          $releases = Invoke-RestMethod -Uri "https://api.github.com/repos/ggerganov/llama.cpp/releases"
          $found = $false
          foreach ($release in $releases) {
            $tag = $release.tag_name
            $assets = $release.assets
            foreach ($asset in $assets) {
              if ($asset.name -like "llama-$tag-bin-win-sycl-x64.zip") {
                $zipUrl = $asset.browser_download_url
                Invoke-WebRequest -Uri $zipUrl -OutFile "llama-$tag-bin-win-sycl-x64.zip"
                Expand-Archive -Path "llama-$tag-bin-win-sycl-x64.zip" -DestinationPath "./temp_llma"
                Remove-Item -Path "llama-$tag-bin-win-sycl-x64.zip"
                $found = $true
                break
              }
            }
            if ($found) {
              break
            }
          }
          if (-not $found) {
            throw "Could not find a release with llama-【release tag】-bin-win-sycl-x64.zip"
          }

      # 5. 将解压后的文件夹重命名为 llma 并移动到克隆项目的根目录
      - name: Rename and move folder
        shell: pwsh
        run: |
          if (Test-Path -Path "./temp_llma") {
            Move-Item -Path "./temp_llma" -Destination "./llma" -Force
            Write-Host "Successfully moved and renamed the folder to llma."
          } else {
            Write-Error "The temp_llma folder does not exist."
            throw
          }

      # 6. 安装 Python 依赖然后应用 pyinstaller app.spec 构建项目
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build project with PyInstaller
        run: pyinstaller app.spec

      # 7. 将构建好的项目打包成 ZIP 文件
      - name: Package built project into ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path dist\* -DestinationPath dist\built-project.zip

      # 8. 上传 ZIP 格式的构建项目
      - name: Upload built project as ZIP
        uses: actions/upload-artifact@v4
        with:
          name: built-project
          path: dist/built-project.zip
