name: Build and Package Project By Doubao

# 允许手动触发工作流
on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: windows-latest  # 使用 Windows 环境，因为要下载 Windows 二进制文件

    steps:
      # 1. 克隆 https://github.com/shinnpuru/VoiceTransl.git 的 main 分支
      - name: Clone VoiceTransl repository
        uses: actions/checkout@v3
        with:
          repository: shinnpuru/VoiceTransl
          ref: main

      # 调试步骤：查看当前目录内容
      - name: List current directory contents
        shell: pwsh
        run: Get-ChildItem

      # 3. 删除克隆项目中的 llma 文件夹
      - name: Delete llama folder
        shell: pwsh
        run: |
          if (Test-Path -Path "llama") {
            try {
              Remove-Item -Path "llama" -Recurse -Force -ErrorAction Stop
              Write-Host "Successfully deleted the llama folder."
            } catch {
              Write-Error "Failed to delete the llama folder: $_"
              throw
            }
          } else {
            Write-Host "The llama folder does not exist."
          }

      # 4. 下载最新的 llama-【release tag】-bin-win-sycl-x64.zip 并解压重命名为 llma
      - name: Download and extract llama binary
        run: |
          $retryCount = 0
          $maxRetries = 3
          do {
            try {
              # 获取所有版本信息
              $releases = Invoke-RestMethod -Uri "https://api.github.com/repos/ggerganov/llama.cpp/releases"
              # 筛选出包含 bin-win-sycl-x64.zip 的版本
              $matchingReleases = $releases | Where-Object { $_.assets.name -like "*bin-win-sycl-x64.zip" }
              if ($matchingReleases.Length -eq 0) {
                throw "No releases found with bin-win-sycl-x64.zip asset."
              }
              # 取最新的匹配版本
              $latestRelease = $matchingReleases[0]
              # 找到对应的资产
              $asset = $latestRelease.assets | Where-Object { $_.name -like "*bin-win-sycl-x64.zip" } | Select-Object -First 1
              $downloadUrl = $asset.browser_download_url
              # 下载文件
              Invoke-WebRequest -Uri $downloadUrl -OutFile "llama.zip"
              break
            } catch {
              $retryCount++
              if ($retryCount -lt $maxRetries) {
                Write-Host "Download failed, retrying in 5 seconds..."
                Start-Sleep -Seconds 5
              } else {
                throw $_
              }
            }
          } while ($retryCount -lt $maxRetries)
          # 解压并重命名
          Expand-Archive -Path "llama.zip" -DestinationPath ".\VoiceTransl\llma"
        shell: powershell
          
      # 调试步骤：查看当前目录内容
      - name: List current directory contents
        shell: pwsh
        run: Get-ChildItem
        
      # 6. 安装 Python 依赖然后应用 pyinstaller app.spec 构建项目
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 可以根据项目需求调整 Python 版本，3.10要加引号不然变3.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build project with PyInstaller
        run: pyinstaller app.spec

      # 7. 将构建好的项目打包成 ZIP 文件
      - name: Package built project into ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path dist\* -DestinationPath dist\built-project.zip

      # 8. 上传 ZIP 格式的构建项目
      - name: Upload built project as ZIP
        uses: actions/upload-artifact@v4
        with:
          name: built-project
          path: dist/built-project.zip
